In [1]:
#cargamos librerias
import ipyrad.analysis as ipa
import pandas as pd
import toyplot
import numpy
import toyplot.pdf

In [2]:
#cargamos nuestros datos .snps.hdf5 
SNPS = "/Users/itziliwi/JN_ipyrad_micro/micro_c85_m95_outfiles/micro_c85_m95.snps.hdf5"

In [3]:
## agrupar individuos con base en los clados del arbol

imap = {
    "PNO": ["eIm_016","eIm_036","eIm_197","eIm_049","eIm_050","eIm_051","eIm_052",
            "eIm_038","eIm_039","eIm_196","eIm_017","eIm_018","eIm_019","eIm_020",
            "eIm_040","eIm_041","eIm_042","eIm_044","eIm_045","eIm_046","eIm_048",
            "eIm_194","eIm_195"],
    "PCE": ["eIm_026","eIm_027","eIm_028","eIm_200","eIm_033","eIm_034","eIm_035",
            "eIm_199","eIm_015","eIm_029","eIm_030","eIm_031","eIm_032","eIm_009",
            "eIm_025","eIm_138","eIm_139","eIm_140", "eIm_141","eIm_143","eIm_145",
            "eIm_146","eIm_147","eIm_148","eIm_149","eIm_150","eIm_151","eIm_152",
            "eIm_153","eIm_162","eIm_163","eIm_164"],
    "PSU": ["eIm_008","eIm_010","eIm_136","eIm_137","eIm_165","eIm_005","eIm_006", "eIm_007"],
    "POR": ["eIm_091","eIm_104","eIm_107","eIm_109","eIm_125",
               "eIm_167","eIm_170"],
    "POO": ["eIm_014","eIm_037", "eIm_043","eIm_047","eIm_054",
               "eIm_065","eIm_066","eIm_084","eIm_187","eIm_193"],
    "ACO": ["eIm_098","eIm_099","eIm_100","eIm_101","eIm_102",
                "eIm_103","eIm_174","eIm_175","eIm_176"],
    "ACE": ["eIm_089","eIm_090","eIm_092","eIm_093","eIm_094",
                "eIm_095","eIm_096","eIm_097","eIm_177"],
    "ATN": ["eIm_105","eIm_106","eIm_108","eIm_110","eIm_111",
               "eIm_112","eIm_113","eIm_114","eIm_115","eIm_116",
                "eIm_117","eIm_118","eIm_119","eIm_120","eIm_121",
                "eIm_122","eIm_123","eIm_124","eIm_126","eIm_127",
               "eIm_128","eIm_129","eIm_130","eIm_131","eIm_132",
                "eIm_133","eIm_134","eIm_135","eIm_166","eIm_168",
                "eIm_169","eIm_171","eIm_172","eIm_173"],
    "ISN": ["eIm_022","eIm_023","eIm_024","eIm_073","eIm_074",
                "eIm_075","eIm_077","eIm_078","eIm_079","eIm_080",
                "eIm_081","eIm_082","eIm_085","eIm_086","eIm_087",
                "eIm_088","eIm_178","eIm_179","eIm_180","eIm_181",
                "eIm_182","eIm_183","eIm_185"],
     "IST": ["eIm_067","eIm_068","eIm_069","eIm_071","eIm_072",
               "eIm_076","eIm_184","eIm_186"],
   "PCH": ["eIm_013","eIm_063","eIm_064","eIm_053","eIm_055", "eIm_056",
            "eIm_057","eIm_058","eIm_059", "eIm_060","eIm_061","eIm_062",
            "eIm_190", "eIm_191", "eIm_192"],
     
}

#definir que al menos el 50% de las muestras tienen datos en cada grupo
minmap = {i: 0.5 for i in imap}

In [4]:
#creamos el objeto PCA con los inputs y parametros necesarios
tool = ipa.pca(
    data=SNPS,
    imap=imap,
    minmap={i: 0 for i in imap},
    mincov=0.75,
    minmaf=0.02,
    # impute_method=12
)

Samples: 178
Sites before filtering: 216104
Filtered (indels): 0
Filtered (bi-allel): 10760
Filtered (mincov): 138093
Filtered (minmap): 0
Filtered (subsample invariant): 65514
Filtered (minor allele frequency): 26064
Filtered (combined): 324357
Sites after filtering: 15794
Sites containing missing values: 15764 (99.81%)
Missing values in SNP matrix: 352099 (12.52%)
SNPs (total): 15794
SNPs (unlinked): 1004
Imputation (Random; sets to ~U[0,1,2]): 33.3%, 33.3%, 33.3%

In [15]:
#corremos el pca
tool.run(100, subsample=True, seed=1245)

Subsampling SNPs: 1004/15794

In [13]:
# guardar los valores de PC en un dataframe
df = pd.DataFrame(tool.pcaxes[0], index=tool.names)

#guardar estos valores en un CSV
#df.to_csv("PCsmicro_clades_2026_0702.csv")

#ver los primeras 10 muestras y los primeros 10 ejes PC
df.iloc[:10, :10].round(2)

             0     1     2      3     4     5     6     7     8      9
eIm_005   4.32  6.07  2.79   0.27  1.65  1.68 -4.88  0.60 -1.73   3.36
eIm_006  -1.11  7.45 -0.87   1.81  1.68 -0.40 -4.31  0.03 -1.52  -0.43
eIm_007   0.82  6.64 -1.19   2.07  3.03  1.02 -6.50 -1.31 -0.92   0.48
eIm_008  10.96 -0.16  8.01  -1.06  0.99  3.54 -5.66  4.15 -1.95  10.75
eIm_009   1.40  8.08 -1.88  -0.32 -5.61  0.91  1.26  0.83  1.49  -0.58
eIm_010   3.85  5.42  2.71   0.19  0.46  0.74 -4.46 -2.46 -0.44   4.95
eIm_013   2.43 -3.21  5.65  -2.32 -0.34  5.07 -0.69 -0.85 -0.56   3.43
eIm_014   0.94  7.70  0.01   1.60  6.24  1.68 -0.17  0.00  4.81  -0.77
eIm_015   4.67  4.93  2.34  -1.67 -6.18 -2.67  1.68  1.73 -1.31   4.95
eIm_016  17.04 -2.45  3.31  20.51 -2.20 -2.43  1.34 -1.38 -1.48  -0.68

In [7]:
vars = tool.variances[0]

pca_summary = pd.DataFrame({
    "PC": range(1, len(vars)+1),
    "Variance": vars,
    "Explained_%": (vars / vars.sum()) * 100
})

pca_summary.head(10)

   PC  Variance  Explained_%
0   1     0.152       15.161
1   2     0.058        5.766
2   3     0.055        5.468
3   4     0.024        2.366
4   5     0.022        2.221
5   6     0.020        1.991
6   7     0.015        1.453
7   8     0.014        1.426
8   9     0.014        1.372
9  10     0.013        1.335

In [8]:
pca_summary.round(3)
pca_summary.round(3).to_csv("PCAgen_summary_20260702.txt", sep="\t", index=False)

In [9]:
colors = ["#D53E4F",
          "#FDAE61",
          "#FFEC8B",
          "#FDD835",
          "#CDE85F",
          "#ABDDA4",
          "#7FFF00",
          "#247067",
          "#3399FF",
          "#99CCFF",
          "#5E4FA2"]

In [17]:
#graficar el eje PC 0 y 1
tool.draw(
    colors=colors,
    width=800,
    height=700,
    #centroids_only=True,
    size=15,
    marker="o",
outfile="PLOT_genPCAmicroMeta_PC0vsPC1_2026_0702.pdf"
);